// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/editor/:projectId": {
    params: {
      "projectId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/editor/:projectId";
  };
  "routes/projects.tsx": {
    id: "routes/projects";
    page: "/";
  };
  "routes/editor.tsx": {
    id: "routes/editor";
    page: "/editor/:projectId";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/projects": typeof import("./src/routes/projects.tsx");
  "routes/editor": typeof import("./src/routes/editor.tsx");
};