import {CompositionWithContextsProps} from './remotion/main';

const UNDOABLE_STATE_CONFIG: CompositionWithContextsProps = {
	tracks: [
		{
			id: 'E3In',
			items: ['JjT8', 'bYNB', 'cSLU', 'dANM'],
			hidden: false,
			muted: false,
		},
	],
	items: {
		bYNB: {
			id: 'bYNB',
			type: 'composite',
			from: 90,
			durationInFrames: 90,
			left: 0,
			top: 0,
			width: 1080,
			height: 1920,
			originalWidth: 1080,
			originalHeight: 1920,
			opacity: 1,
			borderRadius: 0,
			rotation: 0,
			isDraggingInTimeline: false,
			keepAspectRatio: true,
			fadeInDurationInSeconds: 0,
			fadeOutDurationInSeconds: 0,
			name: 'Scale In Demo',
			// Animation: pop in over 25 frames
			childTimeline: {
				tracks: [
					{
						id: 'LgCs',
						items: ['U1hc'],
						hidden: false,
						muted: false,
					},
					{
						id: 'C250',
						items: ['VikT'],
						hidden: false,
						muted: false,
					},
					{
						id: 'CFXL',
						items: ['pkrV'],
						hidden: false,
						muted: false,
					},
				],
				items: {
					pkrV: {
						type: 'solid',
						color: '#bababa',
						durationInFrames: 90,
						from: 0,
						top: 0,
						left: 0,
						width: 1080,
						height: 1920,
						isDraggingInTimeline: false,
						id: 'pkrV',
						opacity: 1,
						borderRadius: 0,
						rotation: 0,
						keepAspectRatio: false,
						fadeInDurationInSeconds: 0,
						fadeOutDurationInSeconds: 0,
						transition: {},
					},
					U1hc: {
						id: 'U1hc',
						durationInFrames: 90,
						top: 183,
						left: 104,
						width: 872,
						height: 1555,
						from: 0,
						type: 'image',
						opacity: 1,
						borderRadius: 50,
						rotation: 0,
						assetId: 'ACvU',
						isDraggingInTimeline: false,
						keepAspectRatio: true,
						fadeInDurationInSeconds: 0,
						fadeOutDurationInSeconds: 0,
						cropLeft: 0,
						cropTop: 0,
						cropRight: 0,
						cropBottom: 0,
						transition: {},
					},
					VikT: {
						type: 'solid',
						color: '#ffffff',
						durationInFrames: 90,
						from: 0,
						top: 176,
						left: 97,
						width: 886,
						height: 1568,
						isDraggingInTimeline: false,
						id: 'VikT',
						opacity: 1,
						borderRadius: 52,
						rotation: 0,
						keepAspectRatio: false,
						fadeInDurationInSeconds: 0,
						fadeOutDurationInSeconds: 0,
						transition: {},
					},
				},
			},
			transition: {},
		},
		JjT8: {
			id: 'JjT8',
			type: 'composite',
			from: 0,
			durationInFrames: 90,
			left: 0,
			top: 0,
			width: 1080,
			height: 1920,
			originalWidth: 1080,
			originalHeight: 1920,
			opacity: 1,
			borderRadius: 0,
			rotation: 0,
			isDraggingInTimeline: false,
			keepAspectRatio: true,
			fadeInDurationInSeconds: 0,
			fadeOutDurationInSeconds: 0,
			name: 'Composite (2 items)',
			// Animation: fade in + slide up over 20 frames
			// animation: {
			// 	type: 'fade-in-slide-up',
			// 	delay: 0,
			// 	duration: 20,
			// },
			childTimeline: {
				tracks: [
					{
						id: '1lQ5',
						items: ['OiLt'],
						hidden: false,
						muted: false,
					},
					{
						id: 'CFXL',
						items: ['pkrV'],
						hidden: false,
						muted: false,
					},
				],
				items: {
					OiLt: {
						id: 'OiLt',
						durationInFrames: 90,
						from: 0,
						type: 'text',
						text: 'Hello World Today',
						color: '#0d0d0d',
						top: 912,
						left: 100,
						width: 880,
						height: 132,
						align: 'center',
						opacity: 1,
						rotation: 0,
						fontFamily: 'Roboto Slab',
						fontSize: 90,
						lineHeight: 1.2,
						letterSpacing: 0,
						resizeOnEdit: true,
						direction: 'ltr',
						fontStyle: {
							variant: 'normal',
							weight: '500',
						},
						isDraggingInTimeline: false,
						strokeWidth: 0,
						strokeColor: '#000000',
						fadeInDurationInSeconds: 0,
						fadeOutDurationInSeconds: 0,
						background: null,
						transition: {},
						// Word-by-word fade in with stagger
					},
					pkrV: {
						type: 'solid',
						color: '#ffffff',
						durationInFrames: 90,
						from: 0,
						top: 0,
						left: 0,
						width: 1080,
						height: 1920,
						isDraggingInTimeline: false,
						id: 'pkrV',
						opacity: 1,
						borderRadius: 0,
						rotation: 0,
						keepAspectRatio: false,
						fadeInDurationInSeconds: 0,
						fadeOutDurationInSeconds: 0,
						transition: {},
					},
				},
			},
			transition: {},
		},
		// Third composite: Slide Up animation
		cSLU: {
			id: 'cSLU',
			type: 'composite',
			from: 180,
			durationInFrames: 90,
			left: 0,
			top: 0,
			width: 1080,
			height: 1920,
			originalWidth: 1080,
			originalHeight: 1920,
			opacity: 1,
			borderRadius: 0,
			rotation: 0,
			isDraggingInTimeline: false,
			keepAspectRatio: true,
			fadeInDurationInSeconds: 0,
			fadeOutDurationInSeconds: 0,
			name: 'Slide Up Demo',
			// Animation: slide in from bottom over 20 frames
			childTimeline: {
				tracks: [
					{
						id: 'trkText3',
						items: ['txt3'],
						hidden: false,
						muted: false,
					},
					{
						id: 'trkSolid3',
						items: ['sol3'],
						hidden: false,
						muted: false,
					},
				],
				items: {
					txt3: {
						id: 'txt3',
						durationInFrames: 90,
						from: 0,
						type: 'text',
						text: 'Bounce Each Word',
						color: '#ffffff',
						top: 860,
						left: 100,
						width: 880,
						height: 200,
						align: 'center',
						opacity: 1,
						rotation: 0,
						fontFamily: 'Roboto Slab',
						fontSize: 100,
						lineHeight: 1.2,
						letterSpacing: 0,
						resizeOnEdit: true,
						direction: 'ltr',
						fontStyle: {
							variant: 'normal',
							weight: '700',
						},
						isDraggingInTimeline: false,
						strokeWidth: 0,
						strokeColor: '#000000',
						fadeInDurationInSeconds: 0,
						fadeOutDurationInSeconds: 0,
						background: null,
						transition: {},
						// Word-by-word fade in
					},
					sol3: {
						type: 'solid',
						color: '#e74c3c',
						durationInFrames: 90,
						from: 0,
						top: 0,
						left: 0,
						width: 1080,
						height: 1920,
						isDraggingInTimeline: false,
						id: 'sol3',
						opacity: 1,
						borderRadius: 0,
						rotation: 0,
						keepAspectRatio: false,
						fadeInDurationInSeconds: 0,
						fadeOutDurationInSeconds: 0,
						transition: {},
					},
				},
			},
			transition: {},
		},
		// Fourth composite: Blur In animation with typewriter text
		dANM: {
			id: 'dANM',
			type: 'composite',
			from: 270,
			durationInFrames: 90,
			left: 0,
			top: 0,
			width: 1080,
			height: 1920,
			originalWidth: 1080,
			originalHeight: 1920,
			opacity: 1,
			borderRadius: 0,
			rotation: 0,
			isDraggingInTimeline: false,
			keepAspectRatio: true,
			fadeInDurationInSeconds: 0,
			fadeOutDurationInSeconds: 0,
			name: 'Blur In Demo',
			// Animation: fade in over 25 frames
			childTimeline: {
				tracks: [
					{
						id: 'trkText4',
						items: ['txt4'],
						hidden: false,
						muted: false,
					},
					{
						id: 'trkSolid4',
						items: ['sol4'],
						hidden: false,
						muted: false,
					},
				],
				items: {
					txt4: {
						id: 'txt4',
						durationInFrames: 90,
						from: 0,
						type: 'text',
						text: 'Typewriter Effect',
						color: '#2c3e50',
						top: 860,
						left: 100,
						width: 880,
						height: 200,
						align: 'center',
						opacity: 1,
						rotation: 0,
						fontFamily: 'Roboto Slab',
						fontSize: 90,
						lineHeight: 1.2,
						letterSpacing: 0,
						resizeOnEdit: true,
						direction: 'ltr',
						fontStyle: {
							variant: 'normal',
							weight: '700',
						},
						isDraggingInTimeline: false,
						strokeWidth: 0,
						strokeColor: '#000000',
						fadeInDurationInSeconds: 0,
						fadeOutDurationInSeconds: 0,
						background: null,
						transition: {},
						// Word-by-word fade in
					},
					sol4: {
						type: 'solid',
						color: '#f1c40f',
						durationInFrames: 90,
						from: 0,
						top: 0,
						left: 0,
						width: 1080,
						height: 1920,
						isDraggingInTimeline: false,
						id: 'sol4',
						opacity: 1,
						borderRadius: 0,
						rotation: 0,
						keepAspectRatio: false,
						fadeInDurationInSeconds: 0,
						fadeOutDurationInSeconds: 0,
						transition: {},
					},
				},
			},
			transition: {},
		},
	},
	assets: {
		ACvU: {
			id: 'ACvU',
			type: 'image',
			filename: 'Pop-Art-Smart-Contract-Icon-midjourney-prompt.webp',
			remoteUrl:
				'https://promptlibrary.org/wp-content/uploads/2025/05/Pop-Art-Smart-Contract-Icon-midjourney-prompt.webp',
			remoteFileKey: null,
			size: 0,
			mimeType: 'image/webp',
			width: null,
			height: null,
			isExternal: true,
			externalErrorCode: 'CORS',
		},
	},
	compositionWidth: 1080,
	compositionHeight: 1920,
	fontInfos: {},
};

export const UNDOABLE_STATE_CONFIG_NEW_TRANSITION: CompositionWithContextsProps =
	{
		tracks: [
			{
				id: 'track_wBJH',
				items: ['template_59JD', 'template_1x5K'],
				hidden: false,
				muted: false,
			},
		],
		items: {
			template_59JD: {
				type: 'solid',
				id: 'template_59JD',
				durationInFrames: 90,
				from: 0,
				left: 0,
				top: 0,
				width: 1080,
				height: 1920,
				color: '#004cff',
				opacity: 1,
				borderRadius: 0,
				rotation: 0,
				keepAspectRatio: false,
				fadeInDurationInSeconds: 0,
				fadeOutDurationInSeconds: 0,
				transition: {
					toNext: {
						type: 'slide',
						durationInFrames: 15,
					},
				},
				isDraggingInTimeline: false,
			},
			template_1x5K: {
				type: 'solid',
				id: 'template_1x5K',
				durationInFrames: 90,
				from: 90,
				left: 0,
				top: 0,
				width: 1080,
				height: 1920,
				color: '#ff0000',
				opacity: 1,
				borderRadius: 0,
				rotation: 0,
				keepAspectRatio: false,
				fadeInDurationInSeconds: 0,
				fadeOutDurationInSeconds: 0,
				transition: {
					toPrev: {
						type: 'slide',
					},
				},
				isDraggingInTimeline: false,
			},
		},
		assets: {},
		compositionWidth: 1080,

		compositionHeight: 1920,
		fontInfos: {},
	};

export const CODE_CONFIG_FOR_REMOTION_STUDIO: CompositionWithContextsProps = {
	tracks: [
		{
			id: 'track_0buW',
			items: ['code_XwXg', 'misc_CjAZ', 'misc_LioB'],
			hidden: false,
			muted: false,
		},
		// {
		// 	id: 'track_tNV2',
		// 	items: ['template_gPkb', 'template_u9fG'],
		// 	hidden: false,
		// 	muted: false,
		// },
	],
	items: {
		code_XwXg: {
			id: 'code_XwXg',
			durationInFrames: 91,
			from: 0,
			type: 'code',
			code: '```ts !\nconst curry = () => {\n\n};\n```',
			processedCode: null,
			top: 0,
			left: 0,
			width: 1080,
			height: 1920,
			opacity: 1,
			rotation: 0,
			fontSize: 60,
			fontFamily: 'Fira Code',
			theme: 'github-dark',
			lineHeight: 1.7,
			tokenTransitionDuration: 0.5,
			disableTokenTransitions: false,
			backgroundColor: '#222137',
			padding: 24,
			borderRadius: 0,
			fadeInDurationInSeconds: 0,
			fadeOutDurationInSeconds: 0,
			isDraggingInTimeline: false,
			transition: {},
			trackId: 'track_0buW',
		},
		misc_CjAZ: {
			id: 'misc_CjAZ',
			durationInFrames: 90,
			from: 91,
			type: 'code',
			code: '```ts !\nconst curry = (fn) => {\n\n};\n\n```',
			processedCode: null,
			top: 0,
			left: 0,
			width: 1080,
			height: 1920,
			opacity: 1,
			rotation: 0,
			fontSize: 60,
			fontFamily: 'Fira Code',
			theme: 'github-dark',
			lineHeight: 1.7,
			tokenTransitionDuration: 0.5,
			disableTokenTransitions: false,
			backgroundColor: '#222137',
			padding: 24,
			borderRadius: 0,
			fadeInDurationInSeconds: 0,
			fadeOutDurationInSeconds: 0,
			isDraggingInTimeline: false,
			transition: {},
			trackId: 'track_0buW',
		},
		misc_LioB: {
			id: 'misc_LioB',
			durationInFrames: 88,
			from: 181,
			type: 'code',
			code: '```ts !\nconst curry = (fn) => {\n    const curried = () => {\n\n    };\n    \n    return curried;\n};\n```',
			processedCode: null,
			top: 0,
			left: 0,
			width: 1080,
			height: 1920,
			opacity: 1,
			rotation: 0,
			fontSize: 48,
			fontFamily: 'Fira Code',
			theme: 'github-dark',
			lineHeight: 1.7,
			tokenTransitionDuration: 1,
			disableTokenTransitions: false,
			backgroundColor: '#222137',
			padding: 24,
			borderRadius: 0,
			fadeInDurationInSeconds: 0,
			fadeOutDurationInSeconds: 0,
			isDraggingInTimeline: false,
			transition: {},
			trackId: 'track_0buW',
		},
		template_gPkb: {
			type: 'solid',
			id: 'template_gPkb',
			durationInFrames: 90,
			from: 0,
			left: 0,
			top: 0,
			width: 1080,
			height: 1920,
			color: '#5b14ff',
			opacity: 1,
			borderRadius: 0,
			rotation: 0,
			keepAspectRatio: false,
			fadeInDurationInSeconds: 0,
			fadeOutDurationInSeconds: 0,
			transition: {
				toNext: {
					type: 'wipe',
					durationInFrames: 30,
					direction: 'from-bottom',
				},
			},
			isDraggingInTimeline: false,
			trackId: 'track_tNV2',
		},
		template_u9fG: {
			type: 'solid',
			id: 'template_u9fG',
			durationInFrames: 90,
			from: 90,
			left: 0,
			top: 0,
			width: 1080,
			height: 1920,
			color: '#f41515',
			opacity: 1,
			borderRadius: 0,
			rotation: 0,
			keepAspectRatio: false,
			fadeInDurationInSeconds: 0,
			fadeOutDurationInSeconds: 0,
			transition: {
				toPrev: {
					type: 'wipe',
					durationInFrames: 30,
					direction: 'from-bottom',
				},
			},
			isDraggingInTimeline: false,
			trackId: 'track_tNV2',
		},
	},
	assets: {},
	fontInfos: {},
	compositionWidth: 1080,
	compositionHeight: 1920,
};
export default UNDOABLE_STATE_CONFIG;
