const GROUP = {
	id: 'nW3K',
	type: 'composite',
	from: 0,
	durationInFrames: 457,
	left: 436.5,
	top: 492,
	width: 1047,
	height: 120,
	originalWidth: 1047,
	originalHeight: 120,
	opacity: 1,
	borderRadius: 0,
	rotation: 0,
	isDraggingInTimeline: false,
	keepAspectRatio: true,
	fadeInDurationInSeconds: 0,
	fadeOutDurationInSeconds: 0,
	name: 'Composite (4 items)',
	childTimeline: {
		tracks: [
			{
				id: 'Vu7k',
				items: ['L5Eu', 'CVUF', 'ENpH', 'Zz21'],
				hidden: false,
				muted: false,
			},
		],
		items: {
			L5Eu: {
				id: 'L5Eu',
				durationInFrames: 100,
				from: 0,
				type: 'text',
				text: 'If you love Hollywood movies,',
				color: '#ffffff',
				top: 0,
				left: 0,
				width: 1047,
				height: 96,
				align: 'center',
				opacity: 1,
				rotation: 0,
				fontFamily: 'DM Serif Text',
				fontSize: 80,
				lineHeight: 1.2,
				letterSpacing: 0,
				resizeOnEdit: true,
				direction: 'ltr',
				fontStyle: {
					variant: 'normal',
					weight: '400',
				},
				isDraggingInTimeline: false,
				strokeWidth: 0,
				strokeColor: '#000000',
				fadeInDurationInSeconds: 0,
				fadeOutDurationInSeconds: 0,
				background: null,
				transition: {},
			},
			CVUF: {
				id: 'CVUF',
				durationInFrames: 119,
				from: 100,
				type: 'text',
				text: 'here are the top three films',
				color: '#ffffff',
				top: 0,
				left: 45.5,
				width: 956,
				height: 96,
				align: 'center',
				opacity: 1,
				rotation: 0,
				fontFamily: 'DM Serif Text',
				fontSize: 80,
				lineHeight: 1.2,
				letterSpacing: 0,
				resizeOnEdit: true,
				direction: 'ltr',
				fontStyle: {
					variant: 'normal',
					weight: '400',
				},
				isDraggingInTimeline: false,
				strokeWidth: 0,
				strokeColor: '#000000',
				fadeInDurationInSeconds: 0,
				fadeOutDurationInSeconds: 0,
				background: null,
				transition: {},
			},
			ENpH: {
				id: 'ENpH',
				durationInFrames: 119,
				from: 219,
				type: 'text',
				text: 'you must watch at least once',
				color: '#ffffff',
				top: 0,
				left: 17,
				width: 1014,
				height: 96,
				align: 'center',
				opacity: 1,
				rotation: 0,
				fontFamily: 'DM Serif Text',
				fontSize: 80,
				lineHeight: 1.2,
				letterSpacing: 0,
				resizeOnEdit: true,
				direction: 'ltr',
				fontStyle: {
					variant: 'normal',
					weight: '400',
				},
				isDraggingInTimeline: false,
				strokeWidth: 0,
				strokeColor: '#000000',
				fadeInDurationInSeconds: 0,
				fadeOutDurationInSeconds: 0,
				background: null,
				transition: {},
			},
			Zz21: {
				id: 'Zz21',
				durationInFrames: 119,
				from: 338,
				type: 'text',
				text: 'in your life.',
				color: '#ffffff',
				top: 0,
				left: 273.5,
				width: 501,
				height: 120,
				align: 'center',
				opacity: 1,
				rotation: 0,
				fontFamily: 'DM Serif Text',
				fontSize: 100,
				lineHeight: 1.2,
				letterSpacing: 0,
				resizeOnEdit: true,
				direction: 'ltr',
				fontStyle: {
					variant: 'normal',
					weight: '400',
				},
				isDraggingInTimeline: false,
				strokeWidth: 0,
				strokeColor: '#000000',
				fadeInDurationInSeconds: 0,
				fadeOutDurationInSeconds: 0,
				background: null,
				transition: {},
			},
		},
	},
	transition: {},
};
